version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  account-mysql:
    build: mysql
    ports:
      - 3306:33060

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  account-service:
    build: account-service
    ports:
      - 6000:6000

  statistics-mongodb:
      build: mongodb
      ports:
        - 27000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  notification-service:
    build: notification-service
    ports:
      - 8000:8000

  monitoring:
    build: monitoring

  gateway:
    build: gateway
