spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://account-mysql:3306/accounts
    username: accounts
    password: ${MYSQL_PASSWORD}

server:
  context-path: /uaa
  port: 5000
