spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://auth-mysql:3306/accounts
    username: accounts
    password: ${MYSQL_PASSWORD}

server:
  context-path: /uaa
  port: 5000
